#!/bin/sh
set -eu

if [ -n "${LABSOS_KIOSK_URL:-}" ]; then
  url="$LABSOS_KIOSK_URL"
elif [ -d /run/live/medium ]; then
  url="http://127.0.0.1/installer"
else
  url="http://127.0.0.1/"
fi

while ! curl -fsS --max-time 2 "$url" >/dev/null 2>&1; do
  sleep 1
done

exec chromium \
  --kiosk \
  --no-first-run \
  --disable-session-crashed-bubble \
  --disable-infobars \
  --disable-translate \
  --check-for-update-interval=31536000 \
  "$url"
