#!/bin/sh
set -eu
input=""
output=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --format|--height|--width) shift 2 ;;
    --output) output="$2"; shift 2 ;;
    *.svg) input="$1"; shift ;;
    *.png) output="$1"; shift ;;
    *) shift ;;
  esac
done
: > "$output"
