#!/usr/bin/env bash
set -Eeuo pipefail
root=$(cd "$(dirname "$0")/../.." && pwd); version=$(cat "$root/VERSION"); out="$root/build/packages"; rm -rf "$out"; mkdir -p "$out"
[[ "$(uname -s)" == Linux ]] || { echo 'ERRO: pacotes devem ser construídos em Ubuntu/Debian Linux ou WSL2.' >&2; exit 1; }
for command in go pnpm curl dpkg-deb; do
  command -v "$command" >/dev/null || { echo "ERRO: comando ausente: $command. Rode make setup em Debian/WSL ou instale-o manualmente." >&2; exit 1; }
done
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
make_deb() { local name=$1; local body=$2; local pkg="$tmp/$name"; mkdir -p "$pkg/DEBIAN"; printf 'Package: %s\nVersion: %s\nSection: admin\nPriority: optional\nArchitecture: amd64\nMaintainer: LabsOS\nDescription: %s\n' "$name" "$version" "$name" > "$pkg/DEBIAN/control"; (cd "$root" && bash -c "set -e; $body"); dpkg-deb --build --root-owner-group "$pkg" "$out/${name}_${version}_amd64.deb" >/dev/null; }
make_deb labsos-core "mkdir -p '$tmp/labsos-core'/etc/labsos '$tmp/labsos-core'/var/lib/labsos/state '$tmp/labsos-core'/opt/labsos/releases '$tmp/labsos-core'/opt/labsos/runtime '$tmp/labsos-core'/DATA '$tmp/labsos-core'/usr/lib/labsos '$tmp/labsos-core'/lib/systemd/system '$tmp/labsos-core'/etc/lightdm '$tmp/labsos-core'/usr/share/xsessions '$tmp/labsos-core'/usr/libexec/docker/cli-plugins; printf '%s\n' '$version' > '$tmp/labsos-core/etc/labsos/version'; printf '%s\n' '{\"version\":\"$version\",\"architecture\":\"amd64\"}' > '$tmp/labsos-core/etc/labsos/release.json'; compose_version=\$(cat packaging/docker/compose.version); curl -fsSL \"https://github.com/docker/compose/releases/download/\$compose_version/docker-compose-linux-x86_64\" -o '$tmp/labsos-core/usr/libexec/docker/cli-plugins/docker-compose'; printf '%s  %s\n' \"\$(cat packaging/docker/compose.sha256)\" '$tmp/labsos-core/usr/libexec/docker/cli-plugins/docker-compose' | sha256sum -c -; chmod 0755 '$tmp/labsos-core/usr/libexec/docker/cli-plugins/docker-compose'; install -m 0644 packaging/labsos-core/issue '$tmp/labsos-core/etc/issue'; install -m 0644 packaging/labsos-core/lightdm.conf '$tmp/labsos-core/etc/lightdm/lightdm.conf'; install -m 0644 packaging/labsos-core/labsos-kiosk.desktop '$tmp/labsos-core/usr/share/xsessions/labsos-kiosk.desktop'; install -m 0644 packaging/labsos-core/labsos-firstboot.service '$tmp/labsos-core/lib/systemd/system/labsos-firstboot.service'; install -m 0644 packaging/labsos-core/labsos-kiosk.service '$tmp/labsos-core/lib/systemd/system/labsos-kiosk.service'; install -m 0755 packaging/labsos-core/labsos-firstboot '$tmp/labsos-core/usr/lib/labsos/labsos-firstboot'; install -m 0755 packaging/labsos-core/labsos-kiosk '$tmp/labsos-core/usr/lib/labsos/labsos-kiosk'; install -m 0755 packaging/labsos-core/labsos-installer '$tmp/labsos-core/usr/lib/labsos/labsos-installer'; install -m 0755 packaging/labsos-core/labsos-installer-backend '$tmp/labsos-core/usr/lib/labsos/labsos-installer-backend'; install -m 0755 packaging/labsos-core/postinst '$tmp/labsos-core/DEBIAN/postinst'"
make_deb labsos-api "mkdir -p '$tmp/labsos-api/opt/labsos/releases/$version/bin' '$tmp/labsos-api/lib/systemd/system' '$tmp/labsos-api/DEBIAN'; (cd backend && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o '$tmp/labsos-api/opt/labsos/releases/$version/bin/labs-api' ./cmd/labs-api); install -m 0644 backend/deploy/labs-api.service '$tmp/labsos-api/lib/systemd/system/labs-api.service'; printf '#!/bin/sh\nln -sfn /opt/labsos/releases/$version/bin/labs-api /usr/local/bin/labs-api\nsystemctl daemon-reload || true\n' > '$tmp/labsos-api/DEBIAN/postinst'; chmod 755 '$tmp/labsos-api/DEBIAN/postinst'"
make_deb labsd "mkdir -p '$tmp/labsd/opt/labsos/releases/$version/bin' '$tmp/labsd/lib/systemd/system' '$tmp/labsd/DEBIAN'; (cd backend && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o '$tmp/labsd/opt/labsos/releases/$version/bin/labsd' ./cmd/labsd); install -m 0644 backend/deploy/labsd.service '$tmp/labsd/lib/systemd/system/labsd.service'; printf '#!/bin/sh\nln -sfn /opt/labsos/releases/$version/bin/labsd /usr/local/bin/labsd\nsystemctl daemon-reload || true\n' > '$tmp/labsd/DEBIAN/postinst'; chmod 755 '$tmp/labsd/DEBIAN/postinst'"
make_deb labsos-dashboard "mkdir -p '$tmp/labsos-dashboard/usr/local/bin' '$tmp/labsos-dashboard/lib/systemd/system'; (cd backend && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o '$tmp/labsos-dashboard/usr/local/bin/labs-dashboard' ./cmd/labs-dashboard); install -m 0644 backend/deploy/labs-dashboard.service '$tmp/labsos-dashboard/lib/systemd/system/labs-dashboard.service'"
make_deb labsos-web "mkdir -p '$tmp/labsos-web/opt/labsos/releases/$version/web'; rm -f '$root/dist'/*.iso '$root/dist'/*.iso.sha256; if [ ! -f '$root/dist/index.html' ]; then pnpm --dir '$root' install --frozen-lockfile; pnpm --dir '$root' build; fi; cp -a '$root/dist'/. '$tmp/labsos-web/opt/labsos/releases/$version/web/'"
make_deb labsos-updater "mkdir -p '$tmp/labsos-updater/usr/lib/labsos' '$tmp/labsos-updater/lib/systemd/system'; install -m 0755 packaging/labsos-updater/labsos-updater '$tmp/labsos-updater/usr/lib/labsos/labsos-updater'"
firmware="$out/firmware-realtek_20250410-2_all.deb"
curl -fsSL https://deb.debian.org/debian/pool/non-free-firmware/f/firmware-nonfree/firmware-realtek_20250410-2_all.deb -o "$firmware"
printf '%s  %s\n' 925755a9b0891c7dc39bbb73d28ab8f7193d37303b5022e8bc9d458b9b4aaa4e "$firmware" | sha256sum -c -
echo "Pacotes em $out"
