import type { StoreApp } from "./types";

export const storeApps: StoreApp[] = [
  {
    id: "jellyfin",
    name: "Jellyfin",
    description: "Servidor de mídia para filmes, séries e músicas.",
    icon: "/app-icons/jellyfin.svg",
    category: "media",
    source: "official",
    version: "10.10.3",
    size: "~180 MB",
    highlights: [
      "Bibliotecas de mídia",
      "Perfis para a família",
      "Reprodução em vários dispositivos",
    ],
  },
  {
    id: "immich",
    name: "Immich",
    description: "Backup e organização de fotos e vídeos.",
    icon: "/app-icons/immich.svg",
    category: "storage",
    source: "official",
    version: "1.129",
    size: "~420 MB",
    highlights: [
      "Backup automático",
      "Álbuns e pesquisa",
      "Acesso para a família",
    ],
  },
  {
    id: "home-assistant",
    name: "Home Assistant",
    description: "Automação para a casa e seus dispositivos.",
    icon: "/app-icons/home-assistant.svg",
    category: "automation",
    source: "official",
    version: "2026.9",
    size: "~350 MB",
    highlights: [
      "Painel da casa",
      "Automação local",
      "Integrações de dispositivos",
    ],
  },
  {
    id: "adguard",
    name: "AdGuard Home",
    description: "Bloqueio de anúncios e proteção da rede.",
    icon: "/app-icons/adguard-home.svg",
    category: "network",
    source: "official",
    version: "0.107.66",
    size: "~90 MB",
    highlights: [
      "Proteção para toda a rede",
      "Filtros configuráveis",
      "Visão de consultas",
    ],
  },
  {
    id: "syncthing",
    name: "Syncthing",
    description: "Sincronização privada de arquivos entre dispositivos.",
    category: "storage",
    source: "official",
    version: "2.0.11",
    size: "~75 MB",
    highlights: [
      "Sincronização direta",
      "Pastas compartilhadas",
      "Sem nuvem obrigatória",
    ],
  },
];
