import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { AlertTriangle, Globe2, ShieldCheck } from "lucide-react"
import { getServices, updateServiceExposure } from "@/api/services"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export function ServicesPage() {
  const client = useQueryClient()
  const query = useQuery({ queryKey: ["services"], queryFn: getServices })
  const mutation = useMutation({ mutationFn: ({ id, exposed }: { id: string; exposed: boolean }) => updateServiceExposure(id, exposed), onSuccess: (result) => { void client.invalidateQueries({ queryKey: ["services"] }); window.dispatchEvent(new CustomEvent("labsos-notice", { detail: result.message })) } })
  return <section className="flex min-w-0 flex-1 flex-col gap-6 p-4 md:p-8"><header><h1 className="text-2xl font-medium md:text-3xl">Serviços na rede</h1><p className="mt-1 text-sm text-muted-foreground">Veja portas e URLs dos Apps. Alterações de firewall e proxy exigem autorização explícita.</p></header>{query.isError && <p role="alert" className="rounded-lg border border-destructive/40 p-4 text-sm">Não foi possível consultar os serviços.</p>}{query.isPending ? <p role="status">Carregando serviços…</p> : (query.data ?? []).length === 0 ? <Card><CardContent className="flex min-h-40 items-center justify-center text-sm text-muted-foreground">Nenhum serviço com porta ou URL detectado.</CardContent></Card> : <div className="grid gap-3">{(query.data ?? []).map((service) => <Card key={service.id}><CardHeader className="flex flex-row items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-base"><Globe2 className="size-4" />{service.name}</CardTitle><span className={`text-xs ${service.conflict ? "text-destructive" : "text-muted-foreground"}`}>{service.conflict ? "Conflito de porta" : service.exposed ? "Exposto" : "Local"}</span></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3"><div className="text-sm text-muted-foreground"><p>Portas: {service.ports?.join(", ") || "não informadas"}</p>{service.url && <p className="truncate">URL: {service.url}</p>}{service.conflict && <p className="mt-1 flex items-center gap-1 text-destructive"><AlertTriangle className="size-3" />Resolva o conflito antes de expor.</p>}</div><Button variant="outline" size="sm" disabled={mutation.isPending || Boolean(service.conflict && !service.exposed)} onClick={() => mutation.mutate({ id: service.id, exposed: !service.exposed })}><ShieldCheck className="mr-1 size-4" />{service.exposed ? "Recolher acesso" : "Solicitar exposição"}</Button></CardContent></Card>)}</div>}</section>
}
